## **1. Numpy 문제 (1)**

* Numpy 선언



In [1]:
# 1) numpy 패키지 로드하여 np로 사용
import numpy as np

## **2. Numpy 문제 (2)**

* 리스트로 배열 만들기



In [2]:
# 1) pythonList 변수에 리스트 선언하기 (리스트 요소는 자유롭게 구성)
pythonList = ["python", "list"]

# 2) npArray 변수에 pythonList 변수를 통해 Numpy 배열 선언
npArray = np.array(pythonList)

# 3) 각각 pythonList, npArray 변수 출력
print(pythonList)
print(npArray)

['python', 'list']
['python' 'list']


## **3. Numpy 문제 (3)**

* 0으로 구성된 2차원 배열 생성



In [4]:
# 1) 0이 10개 채워진 1차원 배열 생성하여 출력
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# 2) 0이 10개 채워진 (5,5) 형태의 2차원 배열 생성하여 출력
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## **4. Numpy 문제 (4)**

* arange & linspace 함수를 사용하여 배열 생성



In [7]:
# 1) [0.  0.5  1. ]
# 2) arange 함수를 사용하여 (1)과 동일한 결과 나오게끔 배열 생성하여 출력
np.arange(0, 1 + 0.5, 0.5)

array([0. , 0.5, 1. ])

In [8]:
# 3) linspace 함수를 사용하여 (1)과 동일한 결과 나오게끔 배열 생성하여 출력
# NOTE: num만큼 n등분
np.linspace(0, 1, num=3)

array([0. , 0.5, 1. ])

## **5. Numpy 문제 (5)**

* 인덱싱(Indexing, 가리킴)과 슬라이싱(Slicing, 잘라냄) 이해



In [9]:
python = np.arange(10)**3
print(python)

[  0   1   8  27  64 125 216 343 512 729]


In [10]:
# 1) python 배열의 2번째 인덱스 출력
python[2]

8

In [11]:
# 2) python 배열의 3~5번 인덱스 출력
python[3:6]

array([ 27,  64, 125])

In [23]:
# 3) python 배열의 64이상의 요소만 출력
# [x] 배열 중 특정 조건 요소만 출력 
python_64 = python >= 64
print(python[python_64])

## 간소화
print([python[python >= 64]])

[ 64 125 216 343 512 729]
[array([ 64, 125, 216, 343, 512, 729])]


## **6. Numpy 문제 (6)**

* 데이터 합치기 & 쪼개기



In [12]:
python_1 = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print(python_1)

[[1 2 3]
 [4 5 6]]


In [13]:
python_2 = np.array([7, 8, 9, 10, 11, 12]).reshape(2, 3)
print(python_2)

[[ 7  8  9]
 [10 11 12]]


In [19]:
# 1) 열을 기준으로 데이터 합쳐서 출력
np.vstack([python_1, python_2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
# 2) 행을 기준으로 데이터 합쳐서 출력
np.hstack([python_1, python_2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [21]:
# 3) python_1 변수에 열을 기준으로 3등분 쪼개어 출력
np.hsplit(python_1, 3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [22]:
# 4) python_1 변수에 행을 기준으로 2등분 쪼개어 출력
# 수업시간엔 안 배운 내용으로 np.vsplit 함수 사용
np.vsplit(python_1, 2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]